version: '3'
services:

  openstack-snapshot:
    build: .
    command: python3 /tmp/source/start.py
    volumes:
      - ./source:/tmp/source
      - ./logs:/tmp/logs
    environment:
      - TERM=linux
      - TERMINFO=/etc/terminfo
